name: 🐞 Bug Report
description: Create a report to help us improve 
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        We welcome bug reports! Please see our contribution guidelines for more information on writing a good bug report.
        
        **Before continuing, have you:**

          * Tried upgrading to newest version of Reflectify, to see if your issue has already been resolved and released?
          * Checked existing open *and* closed issues, to see if the issue has already been reported?
          * Tried reproducing your problem in a new isolated project?
          * Read the documentation
  - type: textarea
    id: background
    attributes:
      label: Description
      description: Please share a clear and concise description of the problem.
      placeholder: Description
    validations:
      required: true
  - type: textarea
    id: repro-steps
    attributes:
      label: Reproduction Steps
      description: |
        Please include minimal steps to reproduce the problem if possible. E.g.: the smallest possible code snippet; or a small project, with steps to run it.
        Always include text as text rather than screenshots so code can easily be copied and will show up in searches.
        Stack Overflow has a great article about [how to create a minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).
      placeholder: Minimal Reproduction
      value: |
        ```csharp
        // Please include a minimal code snippet that reproduces the problem.
        // If you have a small project that reproduces the problem, please include a link to it.
        ```
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: |
        Provide a description of the expected behavior.
      placeholder: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: |
        Provide a description of the actual behavior observed. If applicable please include any error messages or exception stacktraces.
      placeholder: Actual behavior
    validations:
      required: true
  - type: textarea
    id: regression
    attributes:
      label: Regression?
      description: |
        Did this work in a previous release? If you can try a previous release to find out, that can help us narrow down the problem. If you don't know, that's OK.
      placeholder: Regression?
    validations:
      required: false
  - type: textarea
    id: known-workarounds
    attributes:
      label: Known Workarounds
      description: |
        Please provide a description of any known workarounds.
      placeholder: Known Workarounds
    validations:
      required: false
  - type: textarea
    id: configuration
    attributes:
      label: Configuration
      description: |
        Please provide more information on your .NET configuration:
          * Which version of Reflectify are you using?
          * Which .NET runtime and version are you targeting? E.g. .NET framework 4.7.2 or .NET 6.0.
      placeholder: Configuration
    validations:
      required: false
  - type: textarea
    id: other-info
    attributes:
      label: Other information
      description: |
        If you have an idea where the problem might lie, let us know that here. Please include any pointers to code, relevant changes, or related issues you know of.
      placeholder: Other information
    validations:
      required: false
  - type: dropdown
    id: pull-request
    attributes:
      label: Are you willing to help with a pull-request?
      options:
        - "No"
        - "Yes, please assign this issue to me."
    validations:
      required: true