#if !REFLECTIFY_COMPILE
// <autogenerated />
#pragma warning disable
#endif

#nullable disable

// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
namespace Microsoft.CodeAnalysis;

/// <summary>
/// A special attribute recognized by Roslyn, that marks a type as "embedded", meaning it won't ever be visible from
/// other assemblies.
/// </summary>
/// <remarks>
/// Another source-only package compiled into the same assembly may declare this attribute too. Declaring it as
/// <c>partial</c> lets both declarations merge into one type instead of colliding. For that to work, no part may
/// carry a type-level attribute such as <c>[AttributeUsage]</c>, because attributes cannot be repeated across parts.
/// Leaving it off is harmless: <c>AttributeTargets.All</c> is the default.
/// </remarks>
#pragma warning disable RCS1203, MA0010, CA1018 // Deliberately omitted so that duplicate declarations can merge, see above.
internal sealed partial class EmbeddedAttribute : System.Attribute
#pragma warning restore RCS1203, MA0010, CA1018
{
}
