#if !REFLECTIFY_COMPILE
// <autogenerated />
#pragma warning disable
#endif

#nullable disable

// Another source-only package compiled into the same assembly may already declare this attribute. Define
// REFLECTIFY_EXCLUDE_EMBEDDED_ATTRIBUTE to suppress this declaration and use that one instead.
#if !REFLECTIFY_EXCLUDE_EMBEDDED_ATTRIBUTE

using System;
using System.Diagnostics.CodeAnalysis;

// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
namespace Microsoft.CodeAnalysis;

/// <summary>
/// A special attribute recognized by Roslyn, that marks a type as "embedded", meaning it won't ever be visible from
/// other assemblies.
/// </summary>
[AttributeUsage(AttributeTargets.All)]
[ExcludeFromCodeCoverage]
internal sealed class EmbeddedAttribute : Attribute
{
}

#endif
