#if !REFLECTIFY_COMPILE
// <autogenerated />
#pragma warning disable
#endif

#nullable disable

using System.Reflection;

namespace Reflectify;

#if REFLECTIFY_COMPILE
public static class EventInfoExtensions
#else
[global::Microsoft.CodeAnalysis.Embedded]
[global::System.Diagnostics.DebuggerNonUserCode]
internal static class EventInfoExtensions
#endif
{
    /// <summary>
    /// Returns <see langword="true" /> if the event is explicitly implemented on the
    /// <see cref="MemberInfo.DeclaringType"/>, or <see langword="false" /> otherwise.
    /// </summary>
    public static bool IsExplicitlyImplemented(this EventInfo eventInfo)
    {
#if NETCOREAPP2_1_OR_GREATER || NETSTANDARD2_1_OR_GREATER
        return eventInfo.Name.Contains('.');
#else
        return eventInfo.Name.IndexOf('.') != -1;
#endif
    }

    /// <summary>
    /// Returns <see langword="true" /> if the event has a public add or remove accessor, or
    /// <see langword="false" /> otherwise.
    /// </summary>
    public static bool IsPublic(this EventInfo eventInfo)
    {
        return eventInfo.AddMethod is { IsPublic: true } || eventInfo.RemoveMethod is { IsPublic: true };
    }

    /// <summary>
    /// Returns <see langword="true" /> if the event is internal, or <see langword="false" /> otherwise.
    /// </summary>
    /// <param name="eventInfo">The event to check.</param>
    public static bool IsInternal(this EventInfo eventInfo)
    {
        return eventInfo.AddMethod is { IsAssembly: true } or { IsFamilyOrAssembly: true } ||
               eventInfo.RemoveMethod is { IsAssembly: true } or { IsFamilyOrAssembly: true };
    }

    /// <summary>
    /// Returns <see langword="true" /> if the event is abstract, or <see langword="false" /> otherwise.
    /// </summary>
    /// <param name="eventInfo">The event to check.</param>
    public static bool IsAbstract(this EventInfo eventInfo)
    {
        return eventInfo.AddMethod is { IsAbstract: true } || eventInfo.RemoveMethod is { IsAbstract: true };
    }
}
