#if !REFLECTIFY_COMPILE
// <autogenerated />
#pragma warning disable
#endif

#nullable disable

using System;
using System.Reflection;

namespace Reflectify;

#if REFLECTIFY_COMPILE
public static class FieldInfoExtensions
#else
[global::Microsoft.CodeAnalysis.Embedded]
[global::System.Diagnostics.DebuggerNonUserCode]
internal static class FieldInfoExtensions
#endif
{
    /// <summary>
    /// Returns <see langword="true" /> if the field is marked with the C# 11 <see langword="required" />
    /// modifier, or <see langword="false" /> otherwise.
    /// </summary>
    /// <remarks>
    /// The C# compiler emits a <c>System.Runtime.CompilerServices.RequiredMemberAttribute</c> on the member itself
    /// as well as on its declaring type. This method only inspects the attribute on the field itself; it does not
    /// check whether the declaring type as a whole is marked as having required members.
    /// </remarks>
    public static bool IsRequired(this FieldInfo field)
    {
        return MemberInfoExtensions.IsRequired((MemberInfo)field);
    }

    /// <summary>
    /// Determines the nullability of the field, taking into account nullable reference type metadata as well as
    /// nullable value types (see <see cref="TypeExtensions.NullableOrActualType"/>).
    /// </summary>
    public static Nullability GetNullability(this FieldInfo field)
    {
        Type fieldType = field.FieldType;

        Type actualType = fieldType.NullableOrActualType();

        if (actualType != fieldType)
        {
            return Nullability.Nullable;
        }

        if (fieldType.IsValueType)
        {
            return Nullability.NotNull;
        }

#if NET6_0_OR_GREATER
        NullabilityInfo info = new NullabilityInfoContext().Create(field);

        return info.ReadState switch
        {
            NullabilityState.NotNull => Nullability.NotNull,
            NullabilityState.Nullable => Nullability.Nullable,
            _ => Nullability.Unknown
        };
#else
        return NullabilityMetadataReader.GetNullability(fieldType, field.GetCustomAttributes(inherit: false), field.DeclaringType);
#endif
    }

    /// <summary>
    /// Returns <see langword="true" /> if the field is annotated as accepting <see langword="null"/>, either
    /// because it is a nullable reference type or a nullable value type, or <see langword="false" /> otherwise.
    /// </summary>
    public static bool IsNullableReference(this FieldInfo field)
    {
        return field.GetNullability() == Nullability.Nullable;
    }
}
