#if !REFLECTIFY_COMPILE
// <autogenerated />
#pragma warning disable
#endif

#nullable disable

using System;
using System.Linq;
using System.Reflection;

namespace Reflectify;

/// <summary>
/// Specifies whether obsolescence should be evaluated only on the member itself or also on its declaring type.
/// </summary>
public enum ObsoleteMemberFilter
{
    MemberOnly,
    IncludeDeclaringType,
}

#if REFLECTIFY_COMPILE
public static class MemberInfoExtensions
#else
[global::Microsoft.CodeAnalysis.Embedded]
[global::System.Diagnostics.DebuggerNonUserCode]
internal static class MemberInfoExtensions
#endif
{
    public static bool HasAttribute<TAttribute>(this MemberInfo member)
        where TAttribute : Attribute
    {
        // Do not use MemberInfo.IsDefined
        // There is an issue with PropertyInfo and EventInfo preventing the inherit option to work.
        // https://github.com/dotnet/runtime/issues/30219
        return Attribute.IsDefined(member, typeof(TAttribute), inherit: false);
    }

    /// <summary>
    /// Determines whether the member has an attribute of the specified type that matches the predicate.
    /// </summary>
    public static bool HasAttribute<TAttribute>(this MemberInfo member, Func<TAttribute, bool> predicate)
        where TAttribute : Attribute
    {
        if (predicate is null)
        {
            throw new ArgumentNullException(nameof(predicate));
        }

        return member.GetCustomAttributes<TAttribute>(inherit: false).Any(a => predicate(a));
    }

    public static bool HasAttributeInHierarchy<TAttribute>(this MemberInfo member)
        where TAttribute : Attribute
    {
        // Do not use MemberInfo.IsDefined
        // There is an issue with PropertyInfo and EventInfo preventing the inherit option to work.
        // https://github.com/dotnet/runtime/issues/30219
        return Attribute.IsDefined(member, typeof(TAttribute), inherit: true);
    }

    /// <summary>
    /// Determines whether the member or one of its overridden definitions has an attribute of the specified type
    /// that matches the predicate.
    /// </summary>
    public static bool HasAttributeInHierarchy<TAttribute>(this MemberInfo member, Func<TAttribute, bool> predicate)
        where TAttribute : Attribute
    {
        if (predicate is null)
        {
            throw new ArgumentNullException(nameof(predicate));
        }

        return member.GetCustomAttributes<TAttribute>(inherit: true).Any(a => predicate(a));
    }

    /// <summary>
    /// Returns the single attribute of type <typeparamref name="TAttribute"/> that decorates the member,
    /// or <see langword="null" /> if the member is not decorated with such an attribute.
    /// </summary>
    /// <remarks>
    /// If the member is decorated with more than one attribute of type <typeparamref name="TAttribute"/>,
    /// the first one is returned. This method does not consider attributes declared on the member's
    /// overridden or base definitions; use <see cref="GetMatchingAttributes{TAttribute}(MemberInfo)"/> together
    /// with <see cref="HasAttributeInHierarchy{TAttribute}(MemberInfo)"/> if you need to walk the hierarchy.
    /// </remarks>
    public static TAttribute GetAttribute<TAttribute>(this MemberInfo member)
        where TAttribute : Attribute
    {
        return member.GetMatchingAttributes<TAttribute>().FirstOrDefault();
    }

    /// <summary>
    /// Retrieves all attributes of type <typeparamref name="TAttribute"/> that decorate the member.
    /// </summary>
    public static TAttribute[] GetMatchingAttributes<TAttribute>(this MemberInfo member)
        where TAttribute : Attribute
    {
        // Do not use MemberInfo.IsDefined
        // There is an issue with PropertyInfo and EventInfo preventing the inherit option to work.
        // https://github.com/dotnet/runtime/issues/30219
        return Attribute.GetCustomAttributes(member, typeof(TAttribute), inherit: false).Cast<TAttribute>().ToArray();
    }

    /// <summary>
    /// Retrieves all attributes of type <typeparamref name="TAttribute"/> that decorate the member and
    /// match the provided predicate.
    /// </summary>
    public static TAttribute[] GetMatchingAttributes<TAttribute>(this MemberInfo member, Func<TAttribute, bool> predicate)
        where TAttribute : Attribute
    {
        if (predicate is null)
        {
            throw new ArgumentNullException(nameof(predicate));
        }

        return member.GetMatchingAttributes<TAttribute>().Where(predicate).ToArray();
    }

    /// <summary>
    /// Returns <see langword="true" /> if the member is marked as obsolete.
    /// </summary>
    public static bool IsObsolete(this MemberInfo member)
    {
        return member.HasAttribute<ObsoleteAttribute>() ||
               member.DeclaringType?.IsObsolete() == true;
    }

    /// <summary>
    /// Returns <see langword="true" /> if the member is obsolete according to the selected scope.
    /// </summary>
    public static bool IsObsolete(this MemberInfo member, ObsoleteMemberFilter filter)
    {
        if (filter == ObsoleteMemberFilter.MemberOnly)
        {
            return member.HasAttribute<ObsoleteAttribute>();
        }

        return member.IsObsolete();
    }

    /// <summary>
    /// Returns <see langword="true" /> if the member is marked with the C# 11 <see langword="required" />
    /// modifier, or <see langword="false" /> otherwise.
    /// </summary>
    /// <remarks>
    /// The C# compiler emits a <c>System.Runtime.CompilerServices.RequiredMemberAttribute</c> on the member itself
    /// as well as on its declaring type. This method only inspects the attribute on the member itself; it does not
    /// check whether the declaring type as a whole is marked as having required members. On older target
    /// frameworks that attribute type may not be part of the BCL and could instead come from a
    /// PolySharp-polyfilled assembly, so it is matched by full name instead of comparing Type instances
    /// (which would fail across assemblies).
    /// </remarks>
    public static bool IsRequired(this MemberInfo member)
    {
        return member.CustomAttributes.Any(attribute =>
            attribute.AttributeType.FullName == "System.Runtime.CompilerServices.RequiredMemberAttribute");
    }
}
