#if !REFLECTIFY_COMPILE
// <autogenerated />
#pragma warning disable
#endif

#nullable disable

using System;
using System.Reflection;

namespace Reflectify;

/// <summary>
/// Defines the kinds of members you want to get when querying for the fields and properties of a type.
/// </summary>
[Flags]
#if REFLECTIFY_COMPILE
public enum MemberKind
#else
[global::Microsoft.CodeAnalysis.Embedded]
internal enum MemberKind
#endif
{
    None,
    Public = 1,
    Internal = 2,
    ExplicitlyImplemented = 4,
    DefaultInterfaceProperties = 8,
    Static = 16,
    Protected = 32,
    Private = 64
}

#if REFLECTIFY_COMPILE
public static class MemberKindExtensions
#else
[global::Microsoft.CodeAnalysis.Embedded]
[global::System.Diagnostics.DebuggerNonUserCode]
internal static class MemberKindExtensions
#endif
{
    public static BindingFlags ToBindingFlags(this MemberKind kind)
    {
        BindingFlags flags = BindingFlags.Default;

        if ((kind & MemberKind.Public) != MemberKind.None)
        {
            flags |= BindingFlags.Public;
        }

        if ((kind & (MemberKind.Internal | MemberKind.Protected | MemberKind.Private)) != MemberKind.None)
        {
            flags |= BindingFlags.NonPublic;
        }

        return flags;
    }
}
