#if !REFLECTIFY_COMPILE
// <autogenerated />
#pragma warning disable
#endif

#nullable disable

using System;
using System.Linq;
using System.Reflection;

namespace Reflectify;

#if REFLECTIFY_COMPILE
public static class MemberInfoExtensions
#else
[global::Microsoft.CodeAnalysis.Embedded]
[global::System.Diagnostics.DebuggerNonUserCode]
internal static class MemberInfoExtensions
#endif
{
    public static bool HasAttribute<TAttribute>(this MemberInfo member)
        where TAttribute : Attribute
    {
        // Do not use MemberInfo.IsDefined
        // There is an issue with PropertyInfo and EventInfo preventing the inherit option to work.
        // https://github.com/dotnet/runtime/issues/30219
        return Attribute.IsDefined(member, typeof(TAttribute), inherit: false);
    }

    /// <summary>
    /// Determines whether the member has an attribute of the specified type that matches the predicate.
    /// </summary>
    public static bool HasAttribute<TAttribute>(this MemberInfo member, Func<TAttribute, bool> predicate)
        where TAttribute : Attribute
    {
        if (predicate is null)
        {
            throw new ArgumentNullException(nameof(predicate));
        }

        return member.GetCustomAttributes<TAttribute>().Any(a => predicate(a));
    }

    public static bool HasAttributeInHierarchy<TAttribute>(this MemberInfo member)
        where TAttribute : Attribute
    {
        // Do not use MemberInfo.IsDefined
        // There is an issue with PropertyInfo and EventInfo preventing the inherit option to work.
        // https://github.com/dotnet/runtime/issues/30219
        return Attribute.IsDefined(member, typeof(TAttribute), inherit: true);
    }
}
