#if !REFLECTIFY_COMPILE
// <autogenerated />
#pragma warning disable
#endif

#nullable disable

using System.Reflection;

namespace Reflectify;

#if REFLECTIFY_COMPILE
public static class MethodInfoExtensions
#else
[global::Microsoft.CodeAnalysis.Embedded]
[global::System.Diagnostics.DebuggerNonUserCode]
internal static class MethodInfoExtensions
#endif
{
    /// <summary>
    /// Returns <see langword="true" /> if the method is explicitly implemented on the
    /// <see cref="MemberInfo.DeclaringType"/>, or <see langword="false" /> otherwise.
    /// </summary>
    public static bool IsExplicitlyImplemented(this MethodInfo method)
    {
#if NETCOREAPP2_1_OR_GREATER || NETSTANDARD2_1_OR_GREATER
        return method.Name.Contains('.');
#else
        return method.Name.IndexOf('.') != -1;
#endif
    }
}
