#if !REFLECTIFY_COMPILE
// <autogenerated />
#pragma warning disable
#endif

#nullable disable

using System;
using System.Reflection;

namespace Reflectify;

/// <summary>
/// Provides the manual, attribute-based fallback used to determine nullable reference type metadata on target
/// frameworks that don't have access to <c>System.Reflection.NullabilityInfoContext</c> (i.e. everything
/// before .NET 6).
/// </summary>
/// <remarks>
/// The C# compiler encodes nullable reference type information using two compiler-internal attributes that are not
/// part of the public BCL surface: <c>System.Runtime.CompilerServices.NullableAttribute</c> and
/// <c>System.Runtime.CompilerServices.NullableContextAttribute</c>. Because these attributes are embedded
/// per-assembly (rather than shared through a common reference), they must be matched by their full type name
/// instead of via <c>typeof(...)</c>, since a <c>NullableAttribute</c> emitted into one assembly is a different CLR
/// type than one emitted into another. See
/// https://github.com/dotnet/roslyn/blob/main/docs/features/nullable-metadata.md for the specification this logic
/// is based on.
/// </remarks>
#if !REFLECTIFY_COMPILE
[global::Microsoft.CodeAnalysis.Embedded]
#endif
[global::System.Diagnostics.DebuggerNonUserCode]
internal static class NullabilityMetadataReader
{
    private const string NullableAttributeFullName = "System.Runtime.CompilerServices.NullableAttribute";
    private const string NullableContextAttributeFullName = "System.Runtime.CompilerServices.NullableContextAttribute";

    /// <summary>
    /// Determines the <see cref="Nullability"/> of a member of type <paramref name="memberType"/>, given the
    /// attributes declared directly on that member and the type that declares it.
    /// </summary>
    /// <param name="memberType">The type of the property, field or parameter.</param>
    /// <param name="memberAttributes">The custom attributes declared directly on the member.</param>
    /// <param name="declaringType">The type that declares the member, used to walk outward for the ambient nullable context.</param>
    public static Nullability GetNullability(Type memberType, object[] memberAttributes, Type declaringType)
    {
        if (memberType is null)
        {
            return Nullability.Unknown;
        }

        Type actualType = memberType.NullableOrActualType();

        if (actualType != memberType)
        {
            // Nullable<T>, e.g. int?
            return Nullability.Nullable;
        }

        if (memberType.IsValueType)
        {
            // Plain value types, e.g. int, can never be null.
            return Nullability.NotNull;
        }

        byte? flag = GetNullableAttributeFlag(memberAttributes) ?? GetAmbientNullableContextFlag(declaringType);

        return MapFlag(flag);
    }

    private static byte? GetNullableAttributeFlag(object[] attributes)
    {
        foreach (object attribute in attributes)
        {
            if (attribute.GetType().FullName == NullableAttributeFullName)
            {
                FieldInfo field = attribute.GetType().GetField("NullableFlags", BindingFlags.Public | BindingFlags.Instance);

                // The NullableAttribute constructor always populates NullableFlags as a byte[], regardless of
                // whether it was invoked with a single byte or a byte[] (nested generic arguments). The first
                // element always applies to the member itself.
                if (field?.GetValue(attribute) is byte[] { Length: > 0 } flags)
                {
                    return flags[0];
                }
            }
        }

        return null;
    }

    private static byte? GetAmbientNullableContextFlag(Type declaringType)
    {
        for (Type type = declaringType; type is not null; type = type.DeclaringType)
        {
            byte? flag = GetNullableContextFlag(type.GetCustomAttributes(inherit: false));

            if (flag is not null)
            {
                return flag;
            }
        }

        if (declaringType is not null)
        {
            byte? flag = GetNullableContextFlag(declaringType.Module.GetCustomAttributes(inherit: false));

            if (flag is not null)
            {
                return flag;
            }
        }

        return null;
    }

    private static byte? GetNullableContextFlag(object[] attributes)
    {
        foreach (object attribute in attributes)
        {
            if (attribute.GetType().FullName == NullableContextAttributeFullName)
            {
                FieldInfo field = attribute.GetType().GetField("Flag", BindingFlags.Public | BindingFlags.Instance);

                if (field?.GetValue(attribute) is byte value)
                {
                    return value;
                }
            }
        }

        return null;
    }

    private static Nullability MapFlag(byte? flag)
    {
        // Per the Roslyn nullable metadata spec: 0 = oblivious, 1 = not annotated (not null), 2 = annotated (nullable).
        return flag switch
        {
            1 => Nullability.NotNull,
            2 => Nullability.Nullable,
            _ => Nullability.Unknown
        };
    }
}
