#if !REFLECTIFY_COMPILE
// <autogenerated />
#pragma warning disable
#endif

#nullable disable

namespace Reflectify;

/// <summary>
/// Represents the nullability of a member, as determined from the compiler-emitted nullable reference type
/// metadata, or from the fact that the member is a value type (or <see cref="System.Nullable{T}"/>).
/// </summary>
#if REFLECTIFY_COMPILE
public enum Nullability
#else
[global::Microsoft.CodeAnalysis.Embedded]
internal enum Nullability
#endif
{
    /// <summary>
    /// The nullability of the member could not be determined, typically because it was compiled without
    /// nullable reference types enabled (the "oblivious" context).
    /// </summary>
    Unknown,

    /// <summary>
    /// The member is annotated as not allowing <see langword="null"/>.
    /// </summary>
    NotNull,

    /// <summary>
    /// The member is annotated as allowing <see langword="null"/>.
    /// </summary>
    Nullable
}
