#if !REFLECTIFY_COMPILE
// <autogenerated />
#pragma warning disable
#endif

#nullable disable

using System;
using System.Linq;
using System.Reflection;

namespace Reflectify;

#if REFLECTIFY_COMPILE
public static class ParameterInfoExtensions
#else
[global::Microsoft.CodeAnalysis.Embedded]
[global::System.Diagnostics.DebuggerNonUserCode]
internal static class ParameterInfoExtensions
#endif
{
    /// <summary>
    /// Returns <see langword="true" /> if the parameter is decorated with the specific <typeparamref name="TAttribute"/>,
    /// or <see langword="false" /> otherwise.
    /// </summary>
    public static bool HasAttribute<TAttribute>(this ParameterInfo parameter)
        where TAttribute : Attribute
    {
        return parameter.IsDefined(typeof(TAttribute), inherit: false);
    }

    /// <summary>
    /// Returns <see langword="true" /> if the parameter is decorated with the specific <typeparamref name="TAttribute"/> <i>and</i>
    /// that attribute instance matches the predicate, or <see langword="false" /> otherwise.
    /// </summary>
    public static bool HasAttribute<TAttribute>(this ParameterInfo parameter, Func<TAttribute, bool> predicate)
        where TAttribute : Attribute
    {
        if (predicate is null)
        {
            throw new ArgumentNullException(nameof(predicate));
        }

        return parameter.GetCustomAttributes<TAttribute>(inherit: false).Any(predicate);
    }

    /// <summary>
    /// Returns <see langword="true" /> if the parameter or one of its overridden definitions are decorated with the
    /// specific <typeparamref name="TAttribute"/>.
    /// </summary>
    public static bool HasAttributeInHierarchy<TAttribute>(this ParameterInfo parameter)
        where TAttribute : Attribute
    {
        return parameter.IsDefined(typeof(TAttribute), inherit: true);
    }

    /// <summary>
    /// Returns <see langword="true" /> if the parameter or one of its overridden definitions are decorated with the
    /// specific <typeparamref name="TAttribute"/> <i>and</i> that attribute instance matches the predicate, or
    /// <see langword="false" /> otherwise.
    /// </summary>
    /// <remarks>
    /// Note that <see cref="ParameterInfo.GetCustomAttributes(bool)"/> does not reliably walk overridden method
    /// parameters on all runtimes, so this method inherits the same caveat as the non-predicate overload.
    /// </remarks>
    public static bool HasAttributeInHierarchy<TAttribute>(this ParameterInfo parameter, Func<TAttribute, bool> predicate)
        where TAttribute : Attribute
    {
        if (predicate is null)
        {
            throw new ArgumentNullException(nameof(predicate));
        }

        return parameter.GetCustomAttributes<TAttribute>(inherit: true).Any(predicate);
    }

    /// <summary>
    /// Determines the nullability of the parameter, taking into account nullable reference type metadata as well as
    /// nullable value types (see <see cref="TypeExtensions.NullableOrActualType"/>).
    /// </summary>
    public static Nullability GetNullability(this ParameterInfo parameter)
    {
        Type parameterType = parameter.ParameterType;

        Type actualType = parameterType.NullableOrActualType();

        if (actualType != parameterType)
        {
            return Nullability.Nullable;
        }

        if (parameterType.IsValueType)
        {
            return Nullability.NotNull;
        }

#if NET6_0_OR_GREATER
        NullabilityInfo info = new NullabilityInfoContext().Create(parameter);

        return info.ReadState switch
        {
            NullabilityState.NotNull => Nullability.NotNull,
            NullabilityState.Nullable => Nullability.Nullable,
            _ => Nullability.Unknown
        };
#else
        return NullabilityMetadataReader.GetNullability(parameterType, parameter.GetCustomAttributes(inherit: false),
            parameter.Member.DeclaringType);
#endif
    }

    /// <summary>
    /// Returns <see langword="true" /> if the parameter is annotated as accepting <see langword="null"/>, either
    /// because it is a nullable reference type or a nullable value type, or <see langword="false" /> otherwise.
    /// </summary>
    public static bool IsNullableReference(this ParameterInfo parameter)
    {
        return parameter.GetNullability() == Nullability.Nullable;
    }
}
