#if !REFLECTIFY_COMPILE
// <autogenerated />
#pragma warning disable
#endif

#nullable disable

using System.Reflection;

namespace Reflectify;

internal static class PropertyInfoExtensions
{
    /// <summary>
    /// Returns <see langword="true" /> if the property is an indexer, or <see langword="false" /> otherwise.
    /// </summary>
    public static bool IsIndexer(this PropertyInfo member)
    {
        return member.GetIndexParameters().Length != 0;
    }

    /// <summary>
    /// Returns <see langword="true" /> if the property is explicitly implemented on the
    /// <see cref="MemberInfo.DeclaringType"/>, or <see langword="false" /> otherwise.
    /// </summary>
    public static bool IsExplicitlyImplemented(this PropertyInfo prop)
    {
#if NETCOREAPP2_1_OR_GREATER || NETSTANDARD2_1_OR_GREATER
        return prop.Name.Contains('.');
#else
        return prop.Name.IndexOf('.') != -1;
#endif
    }

    /// <summary>
    /// Returns <see langword="true" /> if the property has a public getter or setter, or <see langword="false" /> otherwise.
    /// </summary>
    public static bool IsPublic(this PropertyInfo prop)
    {
        return prop.GetMethod is { IsPublic: true } || prop.SetMethod is { IsPublic: true };
    }

    /// <summary>
    /// Returns <see langword="true" /> if the property is internal, or <see langword="false" /> otherwise.
    /// </summary>
    /// <param name="prop">The property to check.</param>
    public static bool IsInternal(this PropertyInfo prop)
    {
        return prop.GetMethod is { IsAssembly: true } or { IsFamilyOrAssembly: true } ||
               prop.SetMethod is { IsAssembly: true } or { IsFamilyOrAssembly: true };
    }

    /// <summary>
    /// Returns <see langword="true" /> if the property is abstract, or <see langword="false" /> otherwise.
    /// </summary>
    /// <param name="prop">The property to check.</param>
    public static bool IsAbstract(this PropertyInfo prop)
    {
        return prop.GetMethod is { IsAbstract: true } || prop.SetMethod is { IsAbstract: true };
    }
}
