#if !REFLECTIFY_COMPILE
// <autogenerated />
#pragma warning disable
#endif

#nullable disable

using System;
using System.Linq;
using System.Reflection;

namespace Reflectify;

#if REFLECTIFY_COMPILE
public static class PropertyInfoExtensions
#else
[global::Microsoft.CodeAnalysis.Embedded]
[global::System.Diagnostics.DebuggerNonUserCode]
internal static class PropertyInfoExtensions
#endif
{
    /// <summary>
    /// Returns <see langword="true" /> if the property is an indexer, or <see langword="false" /> otherwise.
    /// </summary>
    public static bool IsIndexer(this PropertyInfo member)
    {
        return member.GetIndexParameters().Length != 0;
    }

    /// <summary>
    /// Returns <see langword="true" /> if the property is explicitly implemented on the
    /// <see cref="MemberInfo.DeclaringType"/>, or <see langword="false" /> otherwise.
    /// </summary>
    public static bool IsExplicitlyImplemented(this PropertyInfo prop)
    {
#if NETCOREAPP2_1_OR_GREATER || NETSTANDARD2_1_OR_GREATER
        return prop.Name.Contains('.');
#else
        return prop.Name.IndexOf('.') != -1;
#endif
    }

    /// <summary>
    /// Returns <see langword="true" /> if the property has a public getter or setter, or <see langword="false" /> otherwise.
    /// </summary>
    public static bool IsPublic(this PropertyInfo prop)
    {
        return prop.GetMethod is { IsPublic: true } || prop.SetMethod is { IsPublic: true };
    }

    /// <summary>
    /// Returns <see langword="true" /> if the property is internal, or <see langword="false" /> otherwise.
    /// </summary>
    /// <param name="prop">The property to check.</param>
    public static bool IsInternal(this PropertyInfo prop)
    {
        return prop.GetMethod is { IsAssembly: true } or { IsFamilyOrAssembly: true } ||
               prop.SetMethod is { IsAssembly: true } or { IsFamilyOrAssembly: true };
    }

    /// <summary>
    /// Returns <see langword="true" /> if the property is abstract, or <see langword="false" /> otherwise.
    /// </summary>
    /// <param name="prop">The property to check.</param>
    public static bool IsAbstract(this PropertyInfo prop)
    {
        return prop.GetMethod is { IsAbstract: true } || prop.SetMethod is { IsAbstract: true };
    }

    /// <summary>
    /// Returns <see langword="true" /> if the property is a C# 9 init-only property (i.e. it can only be
    /// assigned through an object initializer or from within a constructor), or <see langword="false" /> otherwise.
    /// </summary>
    public static bool IsInitOnly(this PropertyInfo prop)
    {
        MethodInfo setMethod = prop.SetMethod;

        if (setMethod is null)
        {
            return false;
        }

        // The compiler marks the setter's return parameter with a required custom modifier of type
        // System.Runtime.CompilerServices.IsExternalInit. On older target frameworks that type may not be part of
        // the BCL and could instead come from a PolySharp-polyfilled assembly, so match by full name instead of
        // comparing Type instances (which would fail across assemblies).
        return setMethod.ReturnParameter.GetRequiredCustomModifiers()
            .Any(modifier => modifier.FullName == "System.Runtime.CompilerServices.IsExternalInit");
    }

    /// <summary>
    /// Returns <see langword="true" /> if the property is marked with the C# 11 <see langword="required" />
    /// modifier, or <see langword="false" /> otherwise.
    /// </summary>
    /// <remarks>
    /// The C# compiler emits a <c>System.Runtime.CompilerServices.RequiredMemberAttribute</c> on the member itself
    /// as well as on its declaring type. This method only inspects the attribute on the property itself; it does
    /// not check whether the declaring type as a whole is marked as having required members.
    /// </remarks>
    public static bool IsRequired(this PropertyInfo prop)
    {
        return MemberInfoExtensions.IsRequired((MemberInfo)prop);
    }

    /// <summary>
    /// Returns <see langword="true" /> if the property can be assigned a value outside of an object initializer or
    /// constructor, or <see langword="false" /> otherwise.
    /// </summary>
    /// <remarks>
    /// An init-only property (see <see cref="IsInitOnly"/>) has a setter but is not considered writable.
    /// </remarks>
    public static bool IsWritable(this PropertyInfo prop)
    {
        return prop.SetMethod is not null && !prop.IsInitOnly();
    }

    /// <summary>
    /// Determines the nullability of the property, taking into account nullable reference type metadata as well as
    /// nullable value types (see <see cref="TypeExtensions.NullableOrActualType"/>).
    /// </summary>
    public static Nullability GetNullability(this PropertyInfo prop)
    {
        Type propertyType = prop.PropertyType;

        Type actualType = propertyType.NullableOrActualType();

        if (actualType != propertyType)
        {
            return Nullability.Nullable;
        }

        if (propertyType.IsValueType)
        {
            return Nullability.NotNull;
        }

#if NET6_0_OR_GREATER
        NullabilityInfo info = new NullabilityInfoContext().Create(prop);
        NullabilityState state = prop.GetMethod is not null ? info.ReadState : info.WriteState;

        return state switch
        {
            NullabilityState.NotNull => Nullability.NotNull,
            NullabilityState.Nullable => Nullability.Nullable,
            _ => Nullability.Unknown
        };
#else
        return NullabilityMetadataReader.GetNullability(propertyType, prop.GetCustomAttributes(inherit: false), prop.DeclaringType);
#endif
    }

    /// <summary>
    /// Returns <see langword="true" /> if the property is annotated as accepting <see langword="null"/>, either
    /// because it is a nullable reference type or a nullable value type, or <see langword="false" /> otherwise.
    /// </summary>
    public static bool IsNullableReference(this PropertyInfo prop)
    {
        return prop.GetNullability() == Nullability.Nullable;
    }
}
