#if !REFLECTIFY_COMPILE
// <autogenerated />
#pragma warning disable
#endif

#nullable disable

using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;

namespace Reflectify;

/// <summary>
/// Helper class to get all the public and internal fields and properties from a type.
/// </summary>
#if REFLECTIFY_COMPILE
public sealed class Reflector(Type typeToReflect, MemberKind kind)
#else
[global::Microsoft.CodeAnalysis.Embedded]
[global::System.Diagnostics.DebuggerNonUserCode]
internal sealed class Reflector(Type typeToReflect, MemberKind kind)
#endif
{
    private readonly object lazyLoadingLock = new();
    private volatile PropertyInfo[] cachedProperties;
    private volatile FieldInfo[] cachedFields;
    private volatile EventInfo[] cachedEvents;

    public MemberInfo[] Members => [.. Properties, .. Fields];

    public PropertyInfo[] Properties
    {
        get
        {
            if (cachedProperties is null)
            {
                lock (lazyLoadingLock)
                {
                    if (cachedProperties is null)
                    {
                        cachedProperties = LoadProperties(typeToReflect, kind);
                    }
                }
            }

            return cachedProperties;
        }
    }

    public FieldInfo[] Fields
    {
        get
        {
            if (cachedFields is null)
            {
                lock (lazyLoadingLock)
                {
                    if (cachedFields is null)
                    {
                        cachedFields = LoadFields(typeToReflect, kind);
                    }
                }
            }

            return cachedFields;
        }
    }

    public EventInfo[] Events
    {
        get
        {
            if (cachedEvents is null)
            {
                lock (lazyLoadingLock)
                {
                    if (cachedEvents is null)
                    {
                        cachedEvents = LoadEvents(typeToReflect, kind);
                    }
                }
            }

            return cachedEvents;
        }
    }

    private static PropertyInfo[] LoadProperties(Type typeToReflect, MemberKind kind)
    {
        var selectedProperties = new OrderedPropertyCollection();

        while (typeToReflect != null && typeToReflect != typeof(object))
        {
            BindingFlags flags = BindingFlags.DeclaredOnly | BindingFlags.Public | BindingFlags.NonPublic;
            flags |= (kind & MemberKind.Static) != MemberKind.None ? BindingFlags.Static : BindingFlags.Instance;

            var allProperties = typeToReflect.GetProperties(flags);

            AddNormalProperties(kind, allProperties, selectedProperties);

            AddExplicitlyImplementedProperties(kind, allProperties, selectedProperties);

            AddInterfaceProperties(typeToReflect, kind, flags, selectedProperties);

            // Move to the base type
            typeToReflect = typeToReflect.BaseType;
        }

        return selectedProperties.ToArray();
    }

    private static void AddNormalProperties(MemberKind kind, PropertyInfo[] allProperties, OrderedPropertyCollection selectedProperties)
    {
        if ((kind & (MemberKind.Public | MemberKind.Internal | MemberKind.Protected | MemberKind.Private |
                MemberKind.ExplicitlyImplemented)) != MemberKind.None)
        {
            foreach (var property in allProperties)
            {
                if (HasVisibility(kind, property) && !property.IsExplicitlyImplemented())
                {
                    selectedProperties.AddNormal(property);
                }
            }
        }
    }

    private static bool HasVisibility(MemberKind kind, PropertyInfo prop)
    {
        return ((kind & MemberKind.Public) != MemberKind.None && prop.IsPublic()) ||
               ((kind & MemberKind.Internal) != MemberKind.None && prop.IsInternal()) ||
               ((kind & MemberKind.Protected) != MemberKind.None && prop.IsProtected()) ||
               ((kind & MemberKind.Private) != MemberKind.None && prop.IsPrivate());
    }

    private static void AddExplicitlyImplementedProperties(MemberKind kind, PropertyInfo[] allProperties, OrderedPropertyCollection selectedProperties)
    {
        if ((kind & MemberKind.ExplicitlyImplemented) != MemberKind.None)
        {
            foreach (var property in allProperties)
            {
                if (property.IsExplicitlyImplemented())
                {
                    selectedProperties.AddExplicitlyImplemented(property);
                }
            }
        }
    }

#pragma warning disable AV1561
    private static void AddInterfaceProperties(Type typeToReflect, MemberKind kind, BindingFlags flags, OrderedPropertyCollection selectedProperties)
    {
        if ((kind & MemberKind.DefaultInterfaceProperties) != MemberKind.None || typeToReflect.IsInterface)
        {
            var interfaces = typeToReflect.GetInterfaces();

            foreach (var interfaceType in interfaces)
            {
                foreach (var prop in interfaceType.GetProperties(flags))
                {
                    if (!prop.IsAbstract() || typeToReflect.IsInterface)
                    {
                        selectedProperties.AddFromInterface(prop);
                    }
                }
            }
        }
    }
#pragma warning restore AV1561

    private static FieldInfo[] LoadFields(Type typeToReflect, MemberKind kind)
    {
        var selectedFields = new List<FieldInfo>();
        var collectedFieldNames = new HashSet<string>();

        while (typeToReflect != null && typeToReflect != typeof(object))
        {
            BindingFlags flags = BindingFlags.DeclaredOnly | BindingFlags.Public | BindingFlags.NonPublic;
            flags |= (kind & MemberKind.Static) != MemberKind.None ? BindingFlags.Static : BindingFlags.Instance;

            var files = typeToReflect.GetFields(flags);

            foreach (var field in files)
            {
                if (HasVisibility(kind, field) && collectedFieldNames.Add(field.Name))
                {
                    selectedFields.Add(field);
                }
            }

            // Move to the base type
            typeToReflect = typeToReflect.BaseType;
        }

        return selectedFields.ToArray();
    }

    private static bool HasVisibility(MemberKind kind, FieldInfo field)
    {
        return ((kind & MemberKind.Public) != MemberKind.None && field.IsPublic) ||
               ((kind & MemberKind.Internal) != MemberKind.None && (field.IsAssembly || field.IsFamilyOrAssembly)) ||
               ((kind & MemberKind.Protected) != MemberKind.None && field.IsFamily) ||
               ((kind & MemberKind.Private) != MemberKind.None && field.IsPrivate);
    }

    private static EventInfo[] LoadEvents(Type typeToReflect, MemberKind kind)
    {
        var selectedEvents = new OrderedEventCollection();

        while (typeToReflect != null && typeToReflect != typeof(object))
        {
            BindingFlags flags = BindingFlags.DeclaredOnly | BindingFlags.Public | BindingFlags.NonPublic;
            flags |= (kind & MemberKind.Static) != MemberKind.None ? BindingFlags.Static : BindingFlags.Instance;

            var allEvents = typeToReflect.GetEvents(flags);

            AddNormalEvents(kind, allEvents, selectedEvents);

            AddExplicitlyImplementedEvents(kind, allEvents, selectedEvents);

            AddInterfaceEvents(typeToReflect, kind, flags, selectedEvents);

            // Move to the base type
            typeToReflect = typeToReflect.BaseType;
        }

        return selectedEvents.ToArray();
    }

    private static void AddNormalEvents(MemberKind kind, EventInfo[] allEvents, OrderedEventCollection selectedEvents)
    {
        if ((kind & (MemberKind.Public | MemberKind.Internal | MemberKind.ExplicitlyImplemented)) != MemberKind.None)
        {
            foreach (var @event in allEvents)
            {
                if (HasVisibility(kind, @event) && !@event.IsExplicitlyImplemented())
                {
                    selectedEvents.AddNormal(@event);
                }
            }
        }
    }

    private static bool HasVisibility(MemberKind kind, EventInfo @event)
    {
        return ((kind & MemberKind.Public) != MemberKind.None && @event.IsPublic()) ||
               ((kind & MemberKind.Internal) != MemberKind.None && @event.IsInternal());
    }

    private static void AddExplicitlyImplementedEvents(MemberKind kind, EventInfo[] allEvents, OrderedEventCollection selectedEvents)
    {
        if ((kind & MemberKind.ExplicitlyImplemented) != MemberKind.None)
        {
            foreach (var @event in allEvents)
            {
                if (@event.IsExplicitlyImplemented())
                {
                    selectedEvents.AddExplicitlyImplemented(@event);
                }
            }
        }
    }

#pragma warning disable AV1561
    private static void AddInterfaceEvents(Type typeToReflect, MemberKind kind, BindingFlags flags, OrderedEventCollection selectedEvents)
    {
        if ((kind & MemberKind.DefaultInterfaceProperties) != MemberKind.None || typeToReflect.IsInterface)
        {
            var interfaces = typeToReflect.GetInterfaces();

            foreach (var interfaceType in interfaces)
            {
                foreach (var @event in interfaceType.GetEvents(flags))
                {
                    if (!@event.IsAbstract() || typeToReflect.IsInterface)
                    {
                        selectedEvents.AddFromInterface(@event);
                    }
                }
            }
        }
    }
#pragma warning restore AV1561

    private sealed class OrderedPropertyCollection
    {
        private readonly Dictionary<string, PropertyKind> kindMap = new();
        private readonly List<(string Name, PropertyInfo Property)> propertiesWithName = new();

        public PropertyInfo[] ToArray()
        {
            var result = new PropertyInfo[propertiesWithName.Count];

            for (int i = 0; i < propertiesWithName.Count; i++)
            {
                result[i] = propertiesWithName[i].Property;
            }

            return result;
        }

        private enum PropertyKind
        {
            Normal,
            ExplicitlyImplemented,
            Interface
        }

        public void AddExplicitlyImplemented(PropertyInfo property)
        {
            var name = property.Name.Split('.').Last();

            Add(name, property, PropertyKind.ExplicitlyImplemented);
        }

        public void AddNormal(PropertyInfo property)
        {
            Add(property.Name, property, PropertyKind.Normal);
        }

        public void AddFromInterface(PropertyInfo property)
        {
            Add(property.Name, property, PropertyKind.Interface);
        }

        private void Add(string name, PropertyInfo property, PropertyKind kind)
        {
            if (property.IsIndexer())
            {
                // We explicitly skip indexers
            }
            else if (!kindMap.TryGetValue(name, out var existingKind))
            {
                kindMap[name] = kind;
                propertiesWithName.Add((name, property));
            }
            else if (existingKind == PropertyKind.ExplicitlyImplemented && kind == PropertyKind.Normal)
            {
                // Normal properties have priority over explicitly implemented properties
                kindMap[name] = kind;

                for (int i = 0; i < propertiesWithName.Count; i++)
                {
                    if (propertiesWithName[i].Name == name)
                    {
                        propertiesWithName[i] = (name, property);
                        return;
                    }
                }

                propertiesWithName.Add((name, property));
            }
            else
            {
                // Property with that name already exists
            }
        }
    }

    private sealed class OrderedEventCollection
    {
        private readonly Dictionary<string, EventKind> kindMap = new();
        private readonly List<(string Name, EventInfo Event)> eventsWithName = new();

        public EventInfo[] ToArray()
        {
            var result = new EventInfo[eventsWithName.Count];

            for (int i = 0; i < eventsWithName.Count; i++)
            {
                result[i] = eventsWithName[i].Event;
            }

            return result;
        }

        private enum EventKind
        {
            Normal,
            ExplicitlyImplemented,
            Interface
        }

        public void AddExplicitlyImplemented(EventInfo @event)
        {
            var name = @event.Name.Split('.').Last();

            Add(name, @event, EventKind.ExplicitlyImplemented);
        }

        public void AddNormal(EventInfo @event)
        {
            Add(@event.Name, @event, EventKind.Normal);
        }

        public void AddFromInterface(EventInfo @event)
        {
            Add(@event.Name, @event, EventKind.Interface);
        }

        private void Add(string name, EventInfo @event, EventKind kind)
        {
            if (!kindMap.TryGetValue(name, out var existingKind))
            {
                kindMap[name] = kind;
                eventsWithName.Add((name, @event));
            }
            else if (existingKind == EventKind.ExplicitlyImplemented && kind == EventKind.Normal)
            {
                // Normal events have priority over explicitly implemented events
                kindMap[name] = kind;

                for (int i = 0; i < eventsWithName.Count; i++)
                {
                    if (eventsWithName[i].Name == name)
                    {
                        eventsWithName[i] = (name, @event);
                        return;
                    }
                }

                eventsWithName.Add((name, @event));
            }
            else
            {
                // Event with that name already exists
            }
        }
    }
}
