#if !REFLECTIFY_COMPILE
// <autogenerated />
#pragma warning disable
#endif

#nullable disable

using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;

namespace Reflectify;

/// <summary>
/// Helper class to get all the public and internal fields, properties, events and methods from a type.
/// </summary>
#if REFLECTIFY_COMPILE
public sealed class Reflector(Type typeToReflect, MemberKind kind)
#else
[global::Microsoft.CodeAnalysis.Embedded]
[global::System.Diagnostics.DebuggerNonUserCode]
internal sealed class Reflector(Type typeToReflect, MemberKind kind)
#endif
{
    private readonly object lazyLoadingLock = new();
    private volatile PropertyInfo[] cachedProperties;
    private volatile FieldInfo[] cachedFields;
    private volatile EventInfo[] cachedEvents;
    private volatile MethodInfo[] cachedMethods;

    public MemberInfo[] Members => [.. Properties, .. Fields];

    public PropertyInfo[] Properties
    {
        get
        {
            if (cachedProperties is null)
            {
                lock (lazyLoadingLock)
                {
                    if (cachedProperties is null)
                    {
                        cachedProperties = LoadProperties(typeToReflect, kind);
                    }
                }
            }

            return cachedProperties;
        }
    }

    public FieldInfo[] Fields
    {
        get
        {
            if (cachedFields is null)
            {
                lock (lazyLoadingLock)
                {
                    if (cachedFields is null)
                    {
                        cachedFields = LoadFields(typeToReflect, kind);
                    }
                }
            }

            return cachedFields;
        }
    }

    public EventInfo[] Events
    {
        get
        {
            if (cachedEvents is null)
            {
                lock (lazyLoadingLock)
                {
                    if (cachedEvents is null)
                    {
                        cachedEvents = LoadEvents(typeToReflect, kind);
                    }
                }
            }

            return cachedEvents;
        }
    }

    public MethodInfo[] Methods
    {
        get
        {
            if (cachedMethods is null)
            {
                lock (lazyLoadingLock)
                {
                    if (cachedMethods is null)
                    {
                        cachedMethods = LoadMethods(typeToReflect, kind);
                    }
                }
            }

            return cachedMethods;
        }
    }

    private static PropertyInfo[] LoadProperties(Type typeToReflect, MemberKind kind)
    {
        var selectedProperties = new OrderedPropertyCollection();

        while (typeToReflect != null && typeToReflect != typeof(object))
        {
            BindingFlags flags = BindingFlags.DeclaredOnly | BindingFlags.Public | BindingFlags.NonPublic;
            flags |= (kind & MemberKind.Static) != MemberKind.None ? BindingFlags.Static : BindingFlags.Instance;

            var allProperties = typeToReflect.GetProperties(flags);

            AddNormalProperties(kind, allProperties, selectedProperties);

            AddExplicitlyImplementedProperties(kind, allProperties, selectedProperties);

            AddInterfaceProperties(typeToReflect, kind, flags, selectedProperties);

            // Move to the base type
            typeToReflect = typeToReflect.BaseType;
        }

        return selectedProperties.ToArray();
    }

    private static void AddNormalProperties(MemberKind kind, PropertyInfo[] allProperties, OrderedPropertyCollection selectedProperties)
    {
        if ((kind & (MemberKind.Public | MemberKind.Internal | MemberKind.Protected | MemberKind.Private |
                MemberKind.ExplicitlyImplemented)) != MemberKind.None)
        {
            foreach (var property in allProperties)
            {
                if (HasVisibility(kind, property) && !property.IsExplicitlyImplemented())
                {
                    selectedProperties.AddNormal(property);
                }
            }
        }
    }

    private static bool HasVisibility(MemberKind kind, PropertyInfo prop)
    {
        return ((kind & MemberKind.Public) != MemberKind.None && prop.IsPublic()) ||
               ((kind & MemberKind.Internal) != MemberKind.None && prop.IsInternal()) ||
               ((kind & MemberKind.Protected) != MemberKind.None && prop.IsProtected()) ||
               ((kind & MemberKind.Private) != MemberKind.None && prop.IsPrivate());
    }

    private static void AddExplicitlyImplementedProperties(MemberKind kind, PropertyInfo[] allProperties, OrderedPropertyCollection selectedProperties)
    {
        if ((kind & MemberKind.ExplicitlyImplemented) != MemberKind.None)
        {
            foreach (var property in allProperties)
            {
                if (property.IsExplicitlyImplemented())
                {
                    selectedProperties.AddExplicitlyImplemented(property);
                }
            }
        }
    }

#pragma warning disable AV1561
    private static void AddInterfaceProperties(Type typeToReflect, MemberKind kind, BindingFlags flags, OrderedPropertyCollection selectedProperties)
    {
        if ((kind & MemberKind.DefaultInterfaceProperties) != MemberKind.None || typeToReflect.IsInterface)
        {
            var interfaces = typeToReflect.GetInterfaces();

            foreach (var interfaceType in interfaces)
            {
                foreach (var prop in interfaceType.GetProperties(flags))
                {
                    if (!prop.IsAbstract() || typeToReflect.IsInterface)
                    {
                        selectedProperties.AddFromInterface(prop);
                    }
                }
            }
        }
    }
#pragma warning restore AV1561

    private static FieldInfo[] LoadFields(Type typeToReflect, MemberKind kind)
    {
        var selectedFields = new List<FieldInfo>();
        var collectedFieldNames = new HashSet<string>();

        while (typeToReflect != null && typeToReflect != typeof(object))
        {
            BindingFlags flags = BindingFlags.DeclaredOnly | BindingFlags.Public | BindingFlags.NonPublic;
            flags |= (kind & MemberKind.Static) != MemberKind.None ? BindingFlags.Static : BindingFlags.Instance;

            var files = typeToReflect.GetFields(flags);

            foreach (var field in files)
            {
                if (HasVisibility(kind, field) && collectedFieldNames.Add(field.Name))
                {
                    selectedFields.Add(field);
                }
            }

            // Move to the base type
            typeToReflect = typeToReflect.BaseType;
        }

        return selectedFields.ToArray();
    }

    private static bool HasVisibility(MemberKind kind, FieldInfo field)
    {
        return ((kind & MemberKind.Public) != MemberKind.None && field.IsPublic) ||
               ((kind & MemberKind.Internal) != MemberKind.None && (field.IsAssembly || field.IsFamilyOrAssembly)) ||
               ((kind & MemberKind.Protected) != MemberKind.None && field.IsFamily) ||
               ((kind & MemberKind.Private) != MemberKind.None && field.IsPrivate);
    }

    private static EventInfo[] LoadEvents(Type typeToReflect, MemberKind kind)
    {
        var selectedEvents = new OrderedEventCollection();

        while (typeToReflect != null && typeToReflect != typeof(object))
        {
            BindingFlags flags = BindingFlags.DeclaredOnly | BindingFlags.Public | BindingFlags.NonPublic;
            flags |= (kind & MemberKind.Static) != MemberKind.None ? BindingFlags.Static : BindingFlags.Instance;

            var allEvents = typeToReflect.GetEvents(flags);

            AddNormalEvents(kind, allEvents, selectedEvents);

            AddExplicitlyImplementedEvents(kind, allEvents, selectedEvents);

            AddInterfaceEvents(typeToReflect, kind, flags, selectedEvents);

            // Move to the base type
            typeToReflect = typeToReflect.BaseType;
        }

        return selectedEvents.ToArray();
    }

    private static void AddNormalEvents(MemberKind kind, EventInfo[] allEvents, OrderedEventCollection selectedEvents)
    {
        if ((kind & (MemberKind.Public | MemberKind.Internal | MemberKind.Protected | MemberKind.Private |
                MemberKind.ExplicitlyImplemented)) != MemberKind.None)
        {
            foreach (var @event in allEvents)
            {
                if (HasVisibility(kind, @event) && !@event.IsExplicitlyImplemented())
                {
                    selectedEvents.AddNormal(@event);
                }
            }
        }
    }

    private static bool HasVisibility(MemberKind kind, EventInfo @event)
    {
        return ((kind & MemberKind.Public) != MemberKind.None && @event.IsPublic()) ||
               ((kind & MemberKind.Internal) != MemberKind.None && @event.IsInternal()) ||
               ((kind & MemberKind.Protected) != MemberKind.None && @event.IsProtected()) ||
               ((kind & MemberKind.Private) != MemberKind.None && @event.IsPrivate());
    }

    private static void AddExplicitlyImplementedEvents(MemberKind kind, EventInfo[] allEvents, OrderedEventCollection selectedEvents)
    {
        if ((kind & MemberKind.ExplicitlyImplemented) != MemberKind.None)
        {
            foreach (var @event in allEvents)
            {
                if (@event.IsExplicitlyImplemented())
                {
                    selectedEvents.AddExplicitlyImplemented(@event);
                }
            }
        }
    }

#pragma warning disable AV1561
    private static void AddInterfaceEvents(Type typeToReflect, MemberKind kind, BindingFlags flags, OrderedEventCollection selectedEvents)
    {
        if ((kind & MemberKind.DefaultInterfaceProperties) != MemberKind.None || typeToReflect.IsInterface)
        {
            var interfaces = typeToReflect.GetInterfaces();

            foreach (var interfaceType in interfaces)
            {
                foreach (var @event in interfaceType.GetEvents(flags))
                {
                    if (!@event.IsAbstract() || typeToReflect.IsInterface)
                    {
                        selectedEvents.AddFromInterface(@event);
                    }
                }
            }
        }
    }
#pragma warning restore AV1561

    private static MethodInfo[] LoadMethods(Type typeToReflect, MemberKind kind)
    {
        var selectedMethods = new OrderedMethodCollection();

        while (typeToReflect != null && typeToReflect != typeof(object))
        {
            BindingFlags flags = BindingFlags.DeclaredOnly | BindingFlags.Public | BindingFlags.NonPublic;
            flags |= (kind & MemberKind.Static) != MemberKind.None ? BindingFlags.Static : BindingFlags.Instance;

            // Property/event accessors, indexers, operators and other compiler-generated members are always
            // special-named. They are excluded by default so that GetMethods only returns the methods a caller
            // would normally write and call explicitly.
            var allMethods = typeToReflect.GetMethods(flags).Where(m => !m.IsSpecialName).ToArray();

            AddNormalMethods(kind, allMethods, selectedMethods);

            AddExplicitlyImplementedMethods(kind, allMethods, selectedMethods);

            AddInterfaceMethods(typeToReflect, kind, flags, selectedMethods);

            // Move to the base type
            typeToReflect = typeToReflect.BaseType;
        }

        return selectedMethods.ToArray();
    }

    private static void AddNormalMethods(MemberKind kind, MethodInfo[] allMethods, OrderedMethodCollection selectedMethods)
    {
        if ((kind & (MemberKind.Public | MemberKind.Internal | MemberKind.Protected | MemberKind.Private |
                MemberKind.ExplicitlyImplemented)) != MemberKind.None)
        {
            foreach (var method in allMethods)
            {
                if (HasVisibility(kind, method) && !method.IsExplicitlyImplemented())
                {
                    selectedMethods.AddNormal(method);
                }
            }
        }
    }

    private static bool HasVisibility(MemberKind kind, MethodInfo method)
    {
        return ((kind & MemberKind.Public) != MemberKind.None && method.IsPublic) ||
               ((kind & MemberKind.Internal) != MemberKind.None && (method.IsAssembly || method.IsFamilyOrAssembly)) ||
               ((kind & MemberKind.Protected) != MemberKind.None && method.IsFamily) ||
               ((kind & MemberKind.Private) != MemberKind.None && method.IsPrivate);
    }

    private static void AddExplicitlyImplementedMethods(MemberKind kind, MethodInfo[] allMethods, OrderedMethodCollection selectedMethods)
    {
        if ((kind & MemberKind.ExplicitlyImplemented) != MemberKind.None)
        {
            foreach (var method in allMethods)
            {
                if (method.IsExplicitlyImplemented())
                {
                    selectedMethods.AddExplicitlyImplemented(method);
                }
            }
        }
    }

#pragma warning disable AV1561
    private static void AddInterfaceMethods(Type typeToReflect, MemberKind kind, BindingFlags flags, OrderedMethodCollection selectedMethods)
    {
        if ((kind & MemberKind.DefaultInterfaceProperties) != MemberKind.None || typeToReflect.IsInterface)
        {
            var interfaces = typeToReflect.GetInterfaces();

            foreach (var interfaceType in interfaces)
            {
                foreach (var method in interfaceType.GetMethods(flags).Where(m => !m.IsSpecialName))
                {
                    if (!method.IsAbstract || typeToReflect.IsInterface)
                    {
                        selectedMethods.AddFromInterface(method);
                    }
                }
            }
        }
    }
#pragma warning restore AV1561

    private sealed class OrderedPropertyCollection
    {
        private readonly Dictionary<string, PropertyKind> kindMap = new();
        private readonly List<(string Name, PropertyInfo Property)> propertiesWithName = new();

        public PropertyInfo[] ToArray()
        {
            var result = new PropertyInfo[propertiesWithName.Count];

            for (int i = 0; i < propertiesWithName.Count; i++)
            {
                result[i] = propertiesWithName[i].Property;
            }

            return result;
        }

        private enum PropertyKind
        {
            Normal,
            ExplicitlyImplemented,
            Interface
        }

        public void AddExplicitlyImplemented(PropertyInfo property)
        {
            var name = property.Name.Split('.').Last();

            Add(name, property, PropertyKind.ExplicitlyImplemented);
        }

        public void AddNormal(PropertyInfo property)
        {
            Add(property.Name, property, PropertyKind.Normal);
        }

        public void AddFromInterface(PropertyInfo property)
        {
            Add(property.Name, property, PropertyKind.Interface);
        }

        private void Add(string name, PropertyInfo property, PropertyKind kind)
        {
            if (property.IsIndexer())
            {
                // We explicitly skip indexers
                return;
            }

            if (!kindMap.TryGetValue(name, out var existingKind))
            {
                kindMap[name] = kind;
                propertiesWithName.Add((name, property));
                return;
            }

            if (existingKind == PropertyKind.ExplicitlyImplemented && kind == PropertyKind.Normal)
            {
                kindMap[name] = kind;

                int index = propertiesWithName.FindIndex(propertyWithName => propertyWithName.Name == name);
                propertiesWithName[index] = (name, property);
            }
        }
    }

    private sealed class OrderedEventCollection
    {
        private readonly Dictionary<string, EventKind> kindMap = new();
        private readonly List<(string Name, EventInfo Event)> eventsWithName = new();

        public EventInfo[] ToArray()
        {
            var result = new EventInfo[eventsWithName.Count];

            for (int i = 0; i < eventsWithName.Count; i++)
            {
                result[i] = eventsWithName[i].Event;
            }

            return result;
        }

        private enum EventKind
        {
            Normal,
            ExplicitlyImplemented,
            Interface
        }

        public void AddExplicitlyImplemented(EventInfo @event)
        {
            var name = @event.Name.Split('.').Last();

            Add(name, @event, EventKind.ExplicitlyImplemented);
        }

        public void AddNormal(EventInfo @event)
        {
            Add(@event.Name, @event, EventKind.Normal);
        }

        public void AddFromInterface(EventInfo @event)
        {
            Add(@event.Name, @event, EventKind.Interface);
        }

        private void Add(string name, EventInfo @event, EventKind kind)
        {
            if (!kindMap.TryGetValue(name, out var existingKind))
            {
                kindMap[name] = kind;
                eventsWithName.Add((name, @event));
                return;
            }

            if (existingKind == EventKind.ExplicitlyImplemented && kind == EventKind.Normal)
            {
                kindMap[name] = kind;

                int index = eventsWithName.FindIndex(eventWithName => eventWithName.Name == name);
                eventsWithName[index] = (name, @event);
            }
        }
    }

    private sealed class OrderedMethodCollection
    {
        private readonly Dictionary<string, MethodKind> kindMap = new();
        private readonly List<(string Signature, MethodInfo Method)> methodsWithSignature = new();

        public MethodInfo[] ToArray()
        {
            var result = new MethodInfo[methodsWithSignature.Count];

            for (int i = 0; i < methodsWithSignature.Count; i++)
            {
                result[i] = methodsWithSignature[i].Method;
            }

            return result;
        }

        private enum MethodKind
        {
            Normal,
            ExplicitlyImplemented,
            Interface
        }

        public void AddExplicitlyImplemented(MethodInfo method)
        {
            var name = method.Name.Split('.').Last();

            Add(GetSignature(name, method), method, MethodKind.ExplicitlyImplemented);
        }

        public void AddNormal(MethodInfo method)
        {
            Add(GetSignature(method.Name, method), method, MethodKind.Normal);
        }

        public void AddFromInterface(MethodInfo method)
        {
            Add(GetSignature(method.Name, method), method, MethodKind.Interface);
        }

        // The signature (name, generic arity and parameter types) is what identifies "the same method" across a
        // type hierarchy. Two overloads of the same name are different methods and must both be kept, while an
        // override or a method hidden with `new` shares the signature of the base method it replaces and must be
        // de-duplicated in favor of the most derived one (the one encountered first while walking the hierarchy).
        private static string GetSignature(string name, MethodInfo method)
        {
            string parameters = string.Join(",", method.GetParameters().Select(p => p.ParameterType.FullName));

            return method.IsGenericMethodDefinition
                ? $"{name}`{method.GetGenericArguments().Length}({parameters})"
                : $"{name}({parameters})";
        }

        private void Add(string signature, MethodInfo method, MethodKind kind)
        {
            if (!kindMap.TryGetValue(signature, out var existingKind))
            {
                kindMap[signature] = kind;
                methodsWithSignature.Add((signature, method));
            }
            else if (existingKind == MethodKind.ExplicitlyImplemented && kind == MethodKind.Normal)
            {
                // Normal methods have priority over explicitly implemented methods
                kindMap[signature] = kind;

                for (int i = 0; i < methodsWithSignature.Count; i++)
                {
                    if (methodsWithSignature[i].Signature == signature)
                    {
                        methodsWithSignature[i] = (signature, method);
                        return;
                    }
                }

                methodsWithSignature.Add((signature, method));
            }
            else
            {
                // Method with that signature already exists
            }
        }
    }
}
