#if !REFLECTIFY_COMPILE
// <autogenerated />
#pragma warning disable
#endif

#nullable disable

using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Text;

namespace Reflectify;

#if REFLECTIFY_COMPILE
public static class TypeMetaDataExtensions
#else
[global::Microsoft.CodeAnalysis.Embedded]
[global::System.Diagnostics.DebuggerNonUserCode]
internal static class TypeMetaDataExtensions
#endif
{
    /// <summary>
    /// Returns the name of the type without the generic backtick and the type arguments.
    /// </summary>
    public static string GetNonGenericName(this Type type)
    {
        string name = type.Name;
        int index = name.IndexOf('`');
        return index == -1 ? name : name.Substring(0, index);
    }

    /// <summary>
    /// Returns <see langword="true" /> if the type is derived from an open-generic type, or <see langword="false" /> otherwise.
    /// </summary>
    public static bool IsDerivedFromOpenGeneric(this Type type, Type openGenericType)
    {
        // do not consider a type to be derived from itself
        if (type == openGenericType)
        {
            return false;
        }

        // check subject and its base types against definition
        for (Type baseType = type;
             baseType is not null;
             baseType = baseType.BaseType)
        {
            if (baseType.IsGenericType && baseType.GetGenericTypeDefinition() == openGenericType)
            {
                return true;
            }
        }

        return false;
    }

    /// <summary>
    /// Returns the interfaces that the <paramref name="type"/> implements or inherits from that are concrete
    /// versions of the <paramref name="openGenericType"/>.
    /// </summary>
    public static Type[] GetClosedGenericInterfaces(this Type type, Type openGenericType)
    {
        if (type.IsGenericType && type.GetGenericTypeDefinition() == openGenericType)
        {
            return [type];
        }

        Type[] interfaces = type.GetInterfaces();

        return interfaces
            .Where(t => t.GetInterfaces().Any(x => x.IsGenericType && x.GetGenericTypeDefinition() == openGenericType))
            .ToArray();
    }

    /// <summary>
    /// Returns <see langword="true" /> if the type is decorated with the specific <typeparamref name="TAttribute"/>,
    /// or <see langword="false" /> otherwise.
    /// </summary>
    public static bool HasAttribute<TAttribute>(this Type type)
        where TAttribute : Attribute
    {
        return type.IsDefined(typeof(TAttribute), inherit: false);
    }

    /// <summary>
    /// Returns <see langword="true" /> if the type is decorated with the specific <typeparamref name="TAttribute"/> <i>and</i>
    /// that attribute instance matches the predicate, or <see langword="false" /> otherwise.
    /// </summary>
    public static bool HasAttribute<TAttribute>(this Type type, Func<TAttribute, bool> predicate)
        where TAttribute : Attribute
    {
        if (predicate is null)
        {
            throw new ArgumentNullException(nameof(predicate));
        }

        return type.GetCustomAttributes<TAttribute>(inherit: false).Any(predicate);
    }

    /// <summary>
    /// Returns <see langword="true" /> if the type or one its parents are decorated with the
    /// specific <typeparamref name="TAttribute"/>.
    /// </summary>
    public static bool HasAttributeInHierarchy<TAttribute>(this Type type)
        where TAttribute : Attribute
    {
        return type.IsDefined(typeof(TAttribute), inherit: true);
    }

    /// <summary>
    /// Returns <see langword="true" /> if the type or one its parents are decorated with the
    /// specific <typeparamref name="TAttribute"/> <i>and</i> that attribute instance
    /// matches the predicate. Returns <see langword="false" /> otherwise.
    /// </summary>
    public static bool HasAttributeInHierarchy<TAttribute>(this Type type, Func<TAttribute, bool> predicate)
        where TAttribute : Attribute
    {
        if (predicate is null)
        {
            throw new ArgumentNullException(nameof(predicate));
        }

        return type.GetCustomAttributes<TAttribute>(inherit: true).Any(predicate);
    }

    /// <summary>
    /// Retrieves all custom attributes of the specified type from a class or its inheritance hierarchy.
    /// </summary>
    public static TAttribute[] GetMatchingAttributes<TAttribute>(this Type type)
        where TAttribute : Attribute
    {
        return (TAttribute[])type.GetCustomAttributes<TAttribute>(inherit: true);
    }

    /// <summary>
    /// Retrieves an array of attributes of a specified type that match the provided predicate.
    /// </summary>
    public static TAttribute[] GetMatchingAttributes<TAttribute>(this Type type, Func<TAttribute, bool> predicate)
        where TAttribute : Attribute
    {
        if (predicate is null)
        {
            throw new ArgumentNullException(nameof(predicate));
        }

        return type.GetCustomAttributes<TAttribute>(inherit: true).Where(predicate).ToArray();
    }

    /// <summary>
    /// Returns <see langword="true" /> if the type overrides the Equals method, or <see langword="false" /> otherwise.
    /// </summary>
    public static bool OverridesEquals(this Type type)
    {
        MethodInfo method = type
            .GetMethod("Equals", [typeof(object)]);

        return method is not null
               && method.GetBaseDefinition().DeclaringType != method.DeclaringType;
    }

    /// <summary>
    /// Determines whether the actual type is the same as, or inherits from, the expected type.
    /// </summary>
    /// <remarks>
    /// The expected type can also be an open generic type definition.
    /// </remarks>
    /// <returns><see langword="true" /> if the actual type is the same as, or inherits from, the expected type; otherwise, <see langword="false" />.</returns>
    public static bool IsSameOrInherits<TExpectedType>(this Type actualType)
    {
        return actualType.IsSameOrInherits(typeof(TExpectedType));
    }

    /// <summary>
    /// Determines whether the actual type is the same as, or inherits from, the expected type.
    /// </summary>
    /// <remarks>
    /// The expected type can also be an open generic type definition.
    /// </remarks>
    /// <returns><see langword="true" /> if the actual type is the same as, or inherits from, the expected type; otherwise, <see langword="false" />.</returns>
    public static bool IsSameOrInherits(this Type actualType, Type expectedType)
    {
        return actualType == expectedType ||
               expectedType.IsAssignableFrom(actualType) ||
               (actualType.BaseType is { IsGenericType: true } && actualType.BaseType.GetGenericTypeDefinition() == expectedType);
    }

    /// <summary>
    /// Returns <see langword="true" /> if the type is a delegate type; otherwise, <see langword="false" />.
    /// </summary>
    public static bool IsDelegate(this Type type)
    {
        return typeof(Delegate).IsAssignableFrom(type);
    }

    /// <summary>
    /// Returns <see langword="true" /> if the type is a compiler-generated type, or <see langword="false" /> otherwise.
    /// </summary>
    /// <remarks>
    /// Typical examples of compiler-generated types are anonymous types, tuples, and records.
    /// </remarks>
    public static bool IsCompilerGenerated(this Type type)
    {
        return type.HasAttribute<CompilerGeneratedAttribute>() ||
               type.IsRecord() ||
               type.IsTuple();
    }

    /// <summary>
    /// Returns <see langword="true" /> if the type has a readable name, or <see langword="false" />
    /// if it is a compiler-generated name.
    /// </summary>
    public static bool HasFriendlyName(this Type type)
    {
        return !type.IsAnonymous() && !type.IsTuple();
    }

    /// <summary>
    /// Return <see langword="true" /> if the type is a tuple type; otherwise, <see langword="false" />
    /// </summary>
    public static bool IsTuple(this Type type)
    {
        if (!type.IsGenericType)
        {
            return false;
        }

#if NETCOREAPP2_0_OR_GREATER || NET471_OR_GREATER || NETSTANDARD2_1_OR_GREATER
        return typeof(ITuple).IsAssignableFrom(type);
#else
        Type openType = type.GetGenericTypeDefinition();

        return openType == typeof(ValueTuple<>)
               || openType == typeof(ValueTuple<,>)
               || openType == typeof(ValueTuple<,,>)
               || openType == typeof(ValueTuple<,,,>)
               || openType == typeof(ValueTuple<,,,,>)
               || openType == typeof(ValueTuple<,,,,,>)
               || openType == typeof(ValueTuple<,,,,,,>)
               || (openType == typeof(ValueTuple<,,,,,,,>) && IsTuple(type.GetGenericArguments()[7]))
               || openType == typeof(Tuple<>)
               || openType == typeof(Tuple<,>)
               || openType == typeof(Tuple<,,>)
               || openType == typeof(Tuple<,,,>)
               || openType == typeof(Tuple<,,,,>)
               || openType == typeof(Tuple<,,,,,>)
               || openType == typeof(Tuple<,,,,,,>)
               || (openType == typeof(Tuple<,,,,,,,>) && IsTuple(type.GetGenericArguments()[7]));
#endif
    }

    /// <summary>
    /// Returns <see langword="true" /> if the type is an anonymous type, or <see langword="false" /> otherwise.
    /// </summary>
    public static bool IsAnonymous(this Type type)
    {
        if (type.FullName!.IndexOf("AnonymousType", StringComparison.Ordinal) < 0)
        {
            return false;
        }

        return type.HasAttribute<CompilerGeneratedAttribute>();
    }

    /// <summary>
    /// Return <see langword="true" /> if the type is a struct or class record type; otherwise, <see langword="false" />.
    /// </summary>
    public static bool IsRecord(this Type type)
    {
        return type.IsRecordClass() || type.IsRecordStruct();
    }

    /// <summary>
    /// Returns <see langword="true" /> if the type is a class record type; otherwise, <see langword="false" />.
    /// </summary>
    public static bool IsRecordClass(this Type type)
    {
        return type.GetMethod("<Clone>$", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly) is { } &&
               type.GetProperty("EqualityContract", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly)?
                   .GetMethod?.HasAttribute<CompilerGeneratedAttribute>() == true;
    }

    /// <summary>
    /// Return <see langword="true" /> if the type is a record struct; otherwise, <see langword="false" />
    /// </summary>
    public static bool IsRecordStruct(this Type type)
    {
        // As noted here: https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-10.0/record-structs#open-questions
        // recognizing record structs from metadata is an open point. The following check is based on common sense
        // and heuristic testing, apparently giving good results but not supported by official documentation.
        return type.BaseType == typeof(ValueType) &&
               type.GetMethod("PrintMembers", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly, null,
                   [typeof(StringBuilder)], null) is { } &&
               type.GetMethod("op_Equality", BindingFlags.Static | BindingFlags.Public | BindingFlags.DeclaredOnly, null,
                       [type, type], null)?
                   .HasAttribute<CompilerGeneratedAttribute>() == true;
    }

    /// <summary>
    /// Determines whether the specified type is a KeyValuePair.
    /// </summary>
    /// <param name="type">The type to check.</param>
    /// <returns><see langword="true" /> if the type is a KeyValuePair; otherwise, <see langword="false" />.</returns>
    public static bool IsKeyValuePair(this Type type)
    {
        return type.IsGenericType && type.GetGenericTypeDefinition() == typeof(KeyValuePair<,>);
    }

    /// <summary>
    /// Returns <see langword="true" /> if the type is a struct (i.e., a value type that is not an enum);
    /// otherwise, <see langword="false" />.
    /// </summary>
    public static bool IsStruct(this Type type)
    {
        return type.IsValueType && !type.IsEnum;
    }

    /// <summary>
    /// Returns <see langword="true" /> if the type is a ref struct; otherwise, <see langword="false" />.
    /// </summary>
    /// <remarks>
    /// Returns <see langword="false" /> on .NET versions that do not support ref structs.
    /// </remarks>
    public static bool IsRefStruct(this Type type)
    {
#if NETCOREAPP2_1_OR_GREATER || NETSTANDARD2_1_OR_GREATER
        return type.IsDefined(typeof(IsByRefLikeAttribute), false);
#else
        return false;
#endif
    }

    /// <summary>
    /// Renders the type the way a C# developer would write it, e.g. <c>Dictionary&lt;string, List&lt;int&gt;&gt;</c>.
    /// </summary>
    /// <remarks>
    /// Nullable value types are rendered with a trailing <c>?</c>, arrays respect their rank (e.g. <c>int[,]</c>),
    /// nested types are rendered with a <c>.</c> instead of the CLR <c>+</c>, and open generic type definitions
    /// (like <c>typeof(List&lt;&gt;)</c>) are rendered using the generic parameter's own name (e.g. <c>List&lt;T&gt;</c>).
    /// Common CLR primitive types are mapped to their C# keyword aliases (e.g. <see cref="int" /> instead of
    /// <c>Int32</c>). Types that do not have a friendly name (see <see cref="HasFriendlyName" />), such as
    /// anonymous types and tuples, fall back to a structural rendering, e.g. <c>(int, string)</c> for tuples and
    /// <c>{ Name, Age }</c> for anonymous types.
    /// </remarks>
    public static string GetFriendlyName(this Type type)
    {
        return BuildFriendlyName(type, useFullName: false);
    }

    /// <summary>
    /// Renders the type the way a C# developer would write it, using the full namespace-qualified name, e.g.
    /// <c>System.Collections.Generic.Dictionary&lt;string, System.Collections.Generic.List&lt;int&gt;&gt;</c>.
    /// </summary>
    /// <remarks>
    /// Behaves like <see cref="GetFriendlyName" />, except that the outer type and any nested generic type
    /// arguments are rendered with their full namespace. Common CLR primitive types are still mapped to their
    /// C# keyword aliases, since those keywords do not have a namespace-qualified equivalent.
    /// </remarks>
    public static string GetFullFriendlyName(this Type type)
    {
        return BuildFriendlyName(type, useFullName: true);
    }

    private static string BuildFriendlyName(Type type, bool useFullName)
    {
        if (type.IsGenericParameter)
        {
            return type.Name;
        }

        if (type.IsArray)
        {
            int rank = type.GetArrayRank();
            string commas = new(',', rank - 1);

            return $"{BuildFriendlyName(type.GetElementType(), useFullName)}[{commas}]";
        }

        if (type.IsConstructedGenericType && type.GetGenericTypeDefinition() == typeof(Nullable<>))
        {
            return $"{BuildFriendlyName(type.GetGenericArguments()[0], useFullName)}?";
        }

        if (KeywordAliases.TryGetValue(type, out string alias))
        {
            return alias;
        }

        if (!type.HasFriendlyName())
        {
            return BuildStructuralName(type, useFullName);
        }

        if (type.IsGenericType)
        {
            string typeArguments = string.Join(", ", type.GetGenericArguments().Select(t => BuildFriendlyName(t, useFullName)));

            return $"{BuildSimpleName(type, useFullName)}<{typeArguments}>";
        }

        return BuildSimpleName(type, useFullName);
    }

    private static string BuildSimpleName(Type type, bool useFullName)
    {
        if (useFullName)
        {
            string name = type.FullName ?? type.Name;
            name = name.Replace('+', '.');

            int index = name.IndexOf('`');
            return index == -1 ? name : name.Substring(0, index);
        }

        var nameParts = new List<string>();

        for (Type current = type; current is not null; current = current.DeclaringType)
        {
            nameParts.Insert(0, current.GetNonGenericName());
        }

        return string.Join(".", nameParts);
    }

    private static string BuildStructuralName(Type type, bool useFullName)
    {
        if (type.IsTuple())
        {
            IEnumerable<string> elementNames = type.GetGenericArguments().Select(t => BuildFriendlyName(t, useFullName));

            return $"({string.Join(", ", elementNames)})";
        }

        IEnumerable<string> propertyNames = type.GetProperties(BindingFlags.Public | BindingFlags.Instance)
            .Select(p => p.Name);

        return $"{{ {string.Join(", ", propertyNames)} }}";
    }

    private static readonly Dictionary<Type, string> KeywordAliases = new()
    {
        [typeof(int)] = "int",
        [typeof(string)] = "string",
        [typeof(bool)] = "bool",
        [typeof(double)] = "double",
        [typeof(float)] = "float",
        [typeof(decimal)] = "decimal",
        [typeof(long)] = "long",
        [typeof(short)] = "short",
        [typeof(byte)] = "byte",
        [typeof(sbyte)] = "sbyte",
        [typeof(uint)] = "uint",
        [typeof(ulong)] = "ulong",
        [typeof(ushort)] = "ushort",
        [typeof(char)] = "char",
        [typeof(object)] = "object",
        [typeof(void)] = "void",
    };
}
